# Site settings
author: Gabriel Dennis
title: Beginner SE 
header-img: img/home-bg.png
email: gbdennis96@gmail.com
copyright_name: Gabriel Dennis
description: > # this means to ignore newlines until "baseurl:"
  PT Blog Post
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  gbdennis96

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
